version: '3.8'
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - shareit-network

  server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shareit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - shareit-network

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      SHAREIT_SERVER_URL: http://server:9090
    networks:
      - shareit-network

networks:
  shareit-network:
    driver: bridge