server.port=9090

# Spring JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.sql.init.mode=always

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=postgres
spring.datasource.password=user_user
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.minimumIdle=5

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.ru.practicum.shareit=DEBUG
logging.level.org.hibernate.SQL=DEBUG